/**************************************************************************
 * C S 429 system emulator
 *
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include "err_handler.h"
#include "instr.h"
#include "instr_pipeline.h"
#include "forward.h"
#include "machine.h"
#include "hw_elts.h"

#define SP_NUM 31
#define XZR_NUM 32

extern machine_t guest;
extern mem_status_t dmem_status;

extern int64_t W_wval;

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally.
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */

static comb_logic_t
generate_DXMW_control(opcode_t op,
                      d_ctl_sigs_t *D_sigs, x_ctl_sigs_t *X_sigs, m_ctl_sigs_t *M_sigs, w_ctl_sigs_t *W_sigs)
{

    // Determine source of src 2
    D_sigs->src2_sel = op == OP_STUR;
    // Determine source for valb_sel && sec_CC control signals
    X_sigs->valb_sel = (op >= OP_ADDS_RR && op <= OP_TST_RR && op != OP_SUB_RI && op != OP_MVN);
    X_sigs->set_CC = X_sigs->valb_sel && op != OP_ORR_RR && op != OP_EOR_RR;
    // Determine if data mem read and write are needed
    M_sigs->dmem_read = op == OP_LDUR;
    M_sigs->dmem_write = op == OP_STUR;
    // Destination register selection for write-back
    W_sigs->dst_sel = op == OP_BL;
    W_sigs->wval_sel = op == OP_LDUR;
    // source for wval_sel & write-ack control signals
    W_sigs->w_enable = op == OP_LDUR ||
                       (op > OP_STUR && op < OP_CMP_RR) || (op > OP_CMP_RR && op < OP_TST_RR) || (op > OP_TST_RR && op < OP_B) || op == OP_BL;

    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */

static comb_logic_t
extract_immval(uint32_t insnbits, opcode_t op, int64_t *imm)
{
    switch (op)
    {
    case OP_STUR:
    case OP_LDUR:
        *imm = bitfield_u32(insnbits, 12, 9);
        break;

    case OP_MOVK:
    case OP_MOVZ:
        *imm = bitfield_u32(insnbits, 5, 16);
        break;

    case OP_ADRP:
        *imm = ((bitfield_u32(insnbits, 5, 19) << 2) | bitfield_u32(insnbits, 29, 2)) << 12;
        break;

    case OP_ADD_RI:
    case OP_SUB_RI:
    case OP_ASR:
        *imm = bitfield_u32(insnbits, 10, 12);
        break;

    case OP_LSL:
    case OP_UBFM:
        *imm = 64 - bitfield_u32(insnbits, 16, 6);
        break;

    case OP_LSR:
        *imm = bitfield_u32(insnbits, 16, 6);
        break;

    case OP_B:
        *imm = bitfield_s64(insnbits, 0, 26);
        break;

    default:
        *imm = 0;
        break;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t
decide_alu_op(opcode_t op, alu_op_t *ALU_op)
{
    switch (op)
    {
    case OP_ADD_RI:
    case OP_ADDS_RR:
    case OP_LDUR:
    case OP_STUR:
    case OP_ADRP:
        *ALU_op = PLUS_OP;
        break;

    case OP_SUB_RI:
    case OP_SUBS_RR:
    case OP_CMP_RR:
        *ALU_op = MINUS_OP;
        break;

    case OP_MVN:
        *ALU_op = NEG_OP;
        break;

    case OP_ORR_RR:
        *ALU_op = OR_OP;
        break;

    case OP_EOR_RR:
        *ALU_op = EOR_OP;
        break;

    case OP_ANDS_RR:
    case OP_TST_RR:
        *ALU_op = AND_OP;
        break;

    case OP_MOVK:
    case OP_MOVZ:
        *ALU_op = MOV_OP;
        break;

    case OP_LSL:
    case OP_UBFM:
        *ALU_op = LSL_OP;
        break;

    case OP_LSR:
        *ALU_op = LSR_OP;
        break;

    case OP_ASR:
        *ALU_op = ASR_OP;
        break;

    case OP_BL:
    case OP_RET:
    case OP_B:
    case OP_B_COND:
    case OP_HLT:
    case OP_NOP:
    case OP_ERROR:
        *ALU_op = PASS_A_OP;
        break;
    }

    return;
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */

comb_logic_t
copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src)
{
    dest->dmem_read = src->dmem_read;
    dest->dmem_write = src->dmem_write;
    return;
}

comb_logic_t
copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src)
{
    dest->dst_sel = src->dst_sel;
    dest->w_enable = src->w_enable;
    dest->wval_sel = src->wval_sel;
    return;
}

comb_logic_t
extract_regs(uint32_t insnbits, opcode_t op,
             uint8_t *src1, uint8_t *src2, uint8_t *dst)
{
    set_src_dst_values(src1, src2, dst, insnbits);
    set_src1_dst_values(src1, src2, dst, insnbits);
    process_operations() return;
}

// Processing different operation types and adjust parameters
void process_operations(opcode_t op, uint8_t *src1, uint8_t *src2, uint8_t *dst, uint32_t insnbits)
{
    switch (op)
    {
    case OP_STUR:
        *src2 = insnbits & 0x1FU;
        *src1 = (insnbits >> 5) & 0x1FU;
        *dst = insnbits & 0x1FU;
        break;

    case OP_LDUR:
        *src2 = 0;
        *src1 = (insnbits >> 5) & 0x1FU;
        *dst = insnbits & 0x1FU;
        break;

    case OP_MOVK:
        *dst = bitfield_u32(insnbits, 0, 5);
        set_src1_dst_values(src1, dst, *dst);
        *src2 = 32;
        break;

    case OP_MOVZ:
        *dst = bitfield_u32(insnbits, 0, 5);
        set_src_dst_values(src1, src2, dst, 32);
        break;

    case OP_ADRP:
        *dst = bitfield_u32(insnbits, 0, 5);
        set_src_dst_values(src1, src2, dst, XZR_NUM);
        break;

    case OP_ADDS_RR:
    case OP_SUBS_RR:
    case OP_MVN:
    case OP_ORR_RR:
    case OP_EOR_RR:
    case OP_ANDS_RR:
        *src1 = bitfield_u32(insnbits, 5, 5);
        *src2 = bitfield_u32(insnbits, 16, 5);
        *dst = bitfield_u32(insnbits, 0, 5);
        set_src_dst_values(src1, src2, dst, *dst);
        break;

    case OP_CMP_RR:
    case OP_TST_RR:
        *src1 = bitfield_u32(insnbits, 5, 5);
        *src2 = bitfield_u32(insnbits, 16, 5);
        *dst = XZR_NUM;
        break;

    case OP_ADD_RI:
    case OP_SUB_RI:
        *src1 = bitfield_u32(insnbits, 5, 5);
        *dst = bitfield_u32(insnbits, 0, 5);
        *src2 = 32;
        break;

    case OP_LSL:
    case OP_LSR:
    case OP_UBFM:
    case OP_ASR:
        *src1 = bitfield_u32(insnbits, 5, 5);
        *dst = bitfield_u32(insnbits, 0, 5);
        set_src1_dst_values(src1, dst, *dst);
        *src2 = 32;
        break;

    case OP_RET:
        *src1 = bitfield_u32(insnbits, 5, 5);
        set_src1_dst_values(src1, src1, *src1);
        set_src_dst_values(src2, dst, 32);
        break;

    case OP_B:
    case OP_B_COND:
    case OP_HLT:
        set_src_dst_values(src1, src2, dst, 32);
        break;

    case OP_BL:
        *dst = 30;
        set_src_dst_values(src1, src2, dst, 32);
        break;

    case OP_NOP:
        *src1 = 32;
        *src2 = 32;
        break;

    default:
        *src2 = 32;
    }
}

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 *
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 * Additionally, make sure the register file is updated
 * with W_out's output when you call it in this stage.
 *
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval,
 * and decide_alu_op.
 */

comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out)
{
    out->op = in->op;
    out->print_op = in->print_op;
    out->seq_succ_PC = in->seq_succ_PC;
    out->status = in->status;

    d_ctl_sigs_t D_sigs;
    generate_DXMW_control(in->print_op, &D_sigs, &(out->X_sigs), &(out->M_sigs), &(out->W_sigs));

    // uint8_t dst;
    uint8_t src1;
    uint8_t src2;

    extract_immval(in->insnbits, in->op, &(out->val_imm));
    decide_alu_op(in->print_op, &(out->ALU_op));
    extract_regs(in->insnbits, in->op, &src1, &src2, &(out->dst));
    regfile(src1, src2, W_out->dst, W_wval, W_out->W_sigs.w_enable, &(out->val_a), &(out->val_b));

    forward_reg(src1, src2, X_out->dst, M_out->dst, W_out->dst, M_in->val_ex, M_out->val_ex, W_in->val_mem,
                W_out->val_ex, W_out->val_mem, M_out->W_sigs.wval_sel, W_out->W_sigs.wval_sel, X_out->W_sigs.w_enable,
                M_out->W_sigs.w_enable, W_out->W_sigs.w_enable, &out->val_a, &out->val_b);

    if (in->op == OP_MVN)
    {
        out->val_a = 0;
    }
    if (in->op == OP_B_COND)
    {
        out->cond = bitfield_u32(in->insnbits, 0, 4);
    }
    if (in->op == OP_MOVK || in->op == OP_MOVZ)
    {
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) * 16;
    }
    else
    {
        out->val_hw = 0;
    }
    if (in->op == OP_BL)
    {
        out->val_a = in->seq_succ_PC;
        out->val_b = 0;
    }
    if (in->op == OP_ADRP)
    {
        out->val_a = in->seq_succ_PC;
    }
    if (in->op == OP_HLT)
    {
        in->status = STAT_HLT;
        out->status = STAT_HLT;
    }

    return;
}
